version: "3.8"

services:
  app:
    build: .
    ports:
      - "3000:3000"
    networks:
      - app-network
    volumes:
      - .:/usr/app
      - node_modules
    depends_on:
    - db
  
  db:
    image: mysql:8.0.20
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: db_app
      MYSQL_ROOT_PASSWORD: db_pass
    ports:
      - "3308:3306"
    networks:
      - app-network
    volumes:
      - ".docker/dbdata:/var/lib/mysql"

networks:
  app-network:
    driver: bridge